language: minimal

services: docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed whomey/udagram-api-feed:v1
  - docker tag udagram-api-user whomey/udagram-api-user:v1
  - docker tag udagram-frontend whomey/udagram-frontend:v1
  - docker tag udagram-reverseproxy whomey/udagram-reverseproxy:v1
  - docker push whomey/udagram-api-feed:v1
  - docker push whomey/udagram-api-user:v1
  - docker push whomey/udagram-frontend:v1
  - docker push whomey/udagram-reverseproxy:v1
  
