apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  selector:
    service: backend-feed
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080