apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  selector:
    service: reverseproxy
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080